// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcmxSeSWewos-aWbjd5H6IhF2WlHeljgE',
    appId: '1:738178282427:web:b5bb4409b282bb82a74a9e',
    messagingSenderId: '738178282427',
    projectId: 'loginbackend-762f7',
    authDomain: 'loginbackend-762f7.firebaseapp.com',
    storageBucket: 'loginbackend-762f7.firebasestorage.app',
    measurementId: 'G-TH8518W8NT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGfQPQl1leGaO_KZpndH_tRvx8MocSkWo',
    appId: '1:738178282427:android:3a8ff7182fa82333a74a9e',
    messagingSenderId: '738178282427',
    projectId: 'loginbackend-762f7',
    storageBucket: 'loginbackend-762f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkvdTMCo1EkiRocP53ALn6ZN0fpFsAme8',
    appId: '1:738178282427:ios:eb8f553ab169b8d5a74a9e',
    messagingSenderId: '738178282427',
    projectId: 'loginbackend-762f7',
    storageBucket: 'loginbackend-762f7.firebasestorage.app',
    iosBundleId: 'com.example.registrationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkvdTMCo1EkiRocP53ALn6ZN0fpFsAme8',
    appId: '1:738178282427:ios:eb8f553ab169b8d5a74a9e',
    messagingSenderId: '738178282427',
    projectId: 'loginbackend-762f7',
    storageBucket: 'loginbackend-762f7.firebasestorage.app',
    iosBundleId: 'com.example.registrationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcmxSeSWewos-aWbjd5H6IhF2WlHeljgE',
    appId: '1:738178282427:web:e6304e9a2b1b2a7ea74a9e',
    messagingSenderId: '738178282427',
    projectId: 'loginbackend-762f7',
    authDomain: 'loginbackend-762f7.firebaseapp.com',
    storageBucket: 'loginbackend-762f7.firebasestorage.app',
    measurementId: 'G-FLRVVYWBSJ',
  );
}
